# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b63a3efb51482133917069cad999bef3"
name = "Loyalty and Rewards App"
application_url = "https://loyalty-rewards-app-gxb7.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["orders/paid"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/cancelled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["refunds/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[access_scopes]
scopes = "read_customers,read_discounts,read_orders,write_customers,write_discounts"

[auth]
redirect_urls = [ "https://loyalty-rewards-app-gxb7.onrender.com/auth/callback" ]

[app_proxy]
url = "https://loyalty-rewards-app-gxb7.onrender.com/api/proxy"
subpath = "loyalty"
prefix = "apps"

[pos]
embedded = false
